[inkscape]
target = "/home/colin/.dotfiles/desktop_entries/inkscape.desktop"
link = "/home/colin/.local/share/applications/inkscape.desktop"
[kitty]
target = "/home/colin/.dotfiles/desktop_entries/kitty.desktop"
link = "/home/colin/.local/share/applications/kitty.desktop"
[nvim]
target = "/home/colin/.dotfiles/desktop_entries/nvim.desktop"
link = "/home/colin/.local/share/applications/nvim.desktop"
[obsidian]
target = "/home/colin/.dotfiles/desktop_entries/obsidian.desktop"
link = "/home/colin/.local/share/applications/obsidian.desktop"
[inkscape_icon]
target = "/home/colin/.dotfiles/desktop_entries/icons/inkscape_icon.png"
link = "/home/colin/.local/share/icons/inkscape_icon.png""
[kitty_icon]
target = "/home/colin/.dotfiles/desktop_entries/icons/kitty_icon.png"
link = "/home/colin/.local/share/icons/kitty_icon.png"
[nvim_icon]
target = "/home/colin/.dotfiles/desktop_entries/icons/nvim_icon.png"
link = "/home/colin/.local/share/icons/nvim_icon.png"
[obsidian_icon]
target = "/home/colin/.dotfiles/desktop_entries/icons/obsidian_icon.png"
link = "/home/colin/.local/share/icons/obsidian_icon.png"
