[nvim_init]
target = "/home/colin/.dotfiles/nvim/init.lua"
link = "/home/colin/.config/nvim/init.lua"
[lazy_lock]
target = "/home/colin/.dotfiles/nvim/lazy-lock.json"
link = "/home/colin/.config/nvim/lazy-lock.json"
[keymaps]
target = "/home/colin/.dotfiles/nvim/lua/core/keymaps.lua"
link = "/home/colin/.config/nvim/lua/core/keymaps.lua"
[lazy]
target = "/home/colin/.dotfiles/nvim/lua/core/lazy.lua"
link = "/home/colin/.config/nvim/lua/core/lazy.lua"
[options]
target = "/home/colin/.dotfiles/nvim/lua/core/options.lua"
link = "/home/colin/.config/nvim/lua/core/options.lua"
[catppuccin]
target = "/home/colin/.dotfiles/nvim/lua/plugins/catppuccin.lua"
link = "/home/colin/.config/nvim/lua/plugins/catppuccin.lua"
[everforest]
target = "/home/colin/.dotfiles/nvim/lua/plugins/everforest.lua"
link = "/home/colin/.config/nvim/lua/plugins/everforest.lua"
[lspconfig]
target = "/home/colin/.dotfiles/nvim/lua/plugins/lspconfig.lua"
link = "/home/colin/.config/nvim/lua/plugins/lspconfig.lua"
[lualine]
target = "/home/colin/.dotfiles/nvim/lua/plugins/lualine.lua"
link = "/home/colin/.config/nvim/lua/plugins/lualine.lua"
[mason-lspconfig]
target = "/home/colin/.dotfiles/nvim/lua/plugins/mason-lspconfig.lua"
link = "/home/colin/.config/nvim/lua/plugins/mason-lspconfig.lua"
[mason]
target = "/home/colin/.dotfiles/nvim/lua/plugins/mason.lua"
link = "/home/colin/.config/nvim/lua/plugins/mason.lua"
[nvim-cmp]
target = "/home/colin/.dotfiles/nvim/lua/plugins/nvim-cmp.lua"
link = "/home/colin/.config/nvim/lua/plugins/nvim-cmp.lua"
[treesitter]
target = "/home/colin/.dotfiles/nvim/lua/plugins/treesitter.lua"
link = "/home/colin/.config/nvim/lua/plugins/treesitter.lua"
